### ISSUE TITLE
SC2 screen message during training

### ISSUE THREAD

**Issue by FadyaAbbas** [saizhang0218/TMC#2]
Hi, 
Can you please let me know how to get rid of or delete the message (CHEAT local player KillUnitTagBy..) that appears on the game screen during the training?
With many thanks
![SC2 message](https://user-images.githubusercontent.com/79666658/109339481-f5a02100-7824-11eb-9927-b2ca87700ed2.JPG)

**Comment by saizhang0218** [comment]
I think its the problem of SMAC environment, we dont know how to erase it.
